include: package:lint/strict.yaml

analyzer:
  exclude:
    # - '**.freezed.dart'
    # - '**.g.dart'
    # - '**.config.dart'
    - '**/firebase_options_*.dart'
    - 'lib/generated/**'
  errors:
    invalid_annotation_target: ignore
    unused_result: ignore

linter:
  rules:
    # Util classes are awesome!
    avoid_classes_with_only_static_members: false
    sort_pub_dependencies: false
    sort_unnamed_constructors_first: false
    # Enforce trailing commas for better git diffs and readability
    require_trailing_commas: true
    # This will help enforce trailing commas in long lines
    prefer_single_quotes: true
    # This will help with line length and trailing commas
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_final_fields: true
