name: mystic_app
description: .
publish_to: 'none'

version: 1.1.0+1
environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Localization
  intl: ^0.19.0

  # DI
  get_it: ^8.0.3
  injectable: ^2.5.0

  # State Management
  flutter_bloc: ^9.0.0
  bloc_concurrency: ^0.3.0

  # Models Mapping
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Navigation
  auto_route: ^9.3.0+1

  # Storage
  shared_preferences: ^2.5.2

  # Other
  flutter_svg: ^2.0.17
  vector_graphics: ^1.1.9
  either_dart: ^1.0.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  another_flushbar: ^1.12.31-dev.1
  device_info_plus: ^11.1.1
  package_info_plus: ^8.2.1
  uuid: ^4.5.1
  useful_extensions: ^0.0.1
  countries_utils: ^1.0.1
  permission_handler: ^11.3.1
  flutter_native_splash: ^2.4.5
  flutter_launcher_icons: ^0.14.3
  flutter_markdown: ^0.7.6+2
  http: ^1.3.0
  rxdart: ^0.28.0
  image_picker: ^1.1.2
  share_plus: ^10.1.4
  collection: ^1.18.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.7.0
  cached_network_image: ^3.4.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.9.0
  auto_route_generator: ^9.3.1
  lint: ^2.6.1
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
    - family: TiemposHeadline
      fonts:
        - asset: assets/fonts/TiemposHeadline-Regular.otf
          weight: 400
        - asset: assets/fonts/TiemposHeadline-Medium.otf
          weight: 500
        - asset: assets/fonts/TiemposHeadline-SemiBold.otf
          weight: 600
        - asset: assets/fonts/TiemposHeadline-Bold.otf
          weight: 700
        
flutter_gen:
  output: lib/generated/
  line_length: 120
  integrations:
    flutter_svg: true

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#1a1a1a"
  image: assets/images/splash.png

flutter_launcher_icons:
  image_path: "assets/images/splash.png"
  android: "splash"
  # adaptive_icon_background: "#4f75fb"
  ios: true
  remove_alpha_ios: true

flutter_intl: 
  enabled: true
